"""Add day_of_week and fix models

Revision ID: 46df99c405a6
Revises: 336b51aeca74
Create Date: 2026-03-27 23:52:35.259962

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '46df99c405a6'
down_revision = '336b51aeca74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diet_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_of_week', sa.String(length=20), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_type', sa.String(length=50), nullable=True))

    with op.batch_alter_table('workout_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_of_week', sa.String(length=20), nullable=True))
        batch_op.alter_column('workout_name',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('difficulty',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', mysql.DATETIME(), nullable=True))
        batch_op.alter_column('difficulty',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('workout_name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('day_of_week')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('goal_type')

    with op.batch_alter_table('diet_plans', schema=None) as batch_op:
        batch_op.drop_column('day_of_week')

    # ### end Alembic commands ###
