"""Add image_filename to workout_plans

Revision ID: e95c1e2dd2d3
Revises: 8c6bb9fa8b9a
Create Date: 2026-04-03 21:23:08.352963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e95c1e2dd2d3'
down_revision = '8c6bb9fa8b9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_plans', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
